controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    arm_controller:
      type: position_controllers/JointGroupPositionController

    gripper_controller:
      type: forward_command_controller/ForwardCommandController

    # gripper_controller:
    #   type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"

    command_interfaces:
      - position

    state_interfaces:
      - position

    # open_loop_control: false
    allow_integration_in_goal_trajectories: true
    allow_nonzero_velocity_at_trajectory_end: true

gripper_controller:
  ros__parameters:
    joints:
      - "6"
    interface_name: position
      
    # command_interfaces:
    #   - position

    # state_interfaces:
    #   - position

    # open_loop_control: false
    allow_integration_in_goal_trajectories: true
    allow_nonzero_velocity_at_trajectory_end: true